apiVersion: v1
kind: Secret
metadata:
  name: medview-secrets
  namespace: medview
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ= 
  MEDVIEW_JWT_SECRET: eW91clNlY3JldEtleUhlcmVNYWtlU3VyZUl0SXNBdExlYXN0MjU2Qml0c0xvbmdGb3JTZWN1cml0eXM=